learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
    path('users/', include('users.urls'))
]

learning_logs/urls.py
"""Definiuje wzorce adresów URL dla learning_logs."""

from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
    #Main site
    path('', views.index, name='index'),
    #Topics site
    path('topics', views.topics, name='topics'),
    path('topics/(<int:topic_id>)', views.topic, name='topic'),
    #New topic formula
    path('new_topic', views.new_topic, name='new_topic'),
    #New entry formula
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    #Edit entry
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""Definiuje wzorce adresów URL dla aplikacji users."""

from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    #Dołączenie domyślnych adresów URL uwierzytelniania
    path('', include('django.contrib.auth.urls')),
    #Strona rejestracji
    path('register', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    """Temat poznawany przez użytkownika."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Zwraca reprezentację modelu w postaci ciągu tekstowego."""
        return self.text

class Entry(models.Model):
    """Konkretne informacje o postępie w nauce."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    title = models.CharField(max_length=500)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Zwraca reprezentacje modelu w posiaci ciagu tekstowego."""
        return self.title

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        #kolumny
        fields = ['text']
        #etykiety
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        lables = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404
from .models import Topic, Entry
from .forms import TopicForm, EntryForm

#Functions
def check_topic_owner(topic, request):
    """Chceck if the owner is actual logged user."""
    if topic.owner != request.user:
        raise Http404

#Views
def index(request):
    """Main site of application Learning Log."""
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    """Site with all users topics."""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """Shows single topic and all connected entries."""
    topic = get_object_or_404(Topic, id=topic_id)
    check_topic_owner(topic, request)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """Alows user to create new topic."""
    if request.method != 'POST':
        #Nie przekazano żadnych danych, należy utworzyć pusty formularz
        form = TopicForm()
    else:
        #Przekazano dane za pomocą żądania POST, należy je przetworzyć
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')
    
    #Wyświetlenie pustego formularza
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Allows user to create new entry."""
    topic = Topic.objects.get(id=topic_id)
    check_topic_owner(topic, request)

    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)

    context = {'topic': topic, 'form': form}
    return  render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Allows user to edit created entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    check_topic_owner(topic, request)

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
    
    context = {'form': form, 'entry': entry, 'topic': topic}
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Registration of new users."""
    if request.method != 'POST':
        #Blank formula for user registration
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            #Log in new user and return to main page
            login(request, new_user)
            return redirect('learning_logs:index')
    
    #Prints blank formula
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="pl">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width", initial-scale="1"
        shrink-to-fit="no">
        <title>Learning Log</title>

        {% bootstrap_css %}
        {% bootstrap_javascript jquery='full' %}
    </head>

    <body>
        <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
            <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
                Learning Log</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class='navbar-toggler-icon'></span></button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'learning_logs:topics' %}">Topics</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <span class="navbar-text">Hi, {{ user.username }}.</span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        <main role="main" class="container">
            <div class="pb-2 mb-2 border-bottom">
                {% block page_header %}{% endblock page_header %}
            </div>
            <div>
                {% block content %}{% endblock content %}
            </div>
        </main>
    </body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
<h2>Edit entry</h2>
{% endblock page_header %}



{% block content %}
<p><h6><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h6></p>

<form method="post" action="{% url 'learning_logs:edit_entry' entry.id %}" class='form'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name="'submit" class="btn btn-primary">Save changes</button>
    {% endbuttons %}
</form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
<div class="jumbotron">
    <h1 class="display-3">Monit your progress while learning</h1>

    <p class="lead">Create an account to start using Learning Log application
        to keep all learned lessons in one place!</p>
    
    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">
        Create new account &raquo;</a>  
</div>

{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
<h2>Create new entry in {{ topic }}</h2>
{% endblock page_header %}

{% block content %}
<form method='post' action="{% url 'learning_logs:new_entry' topic.id %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name="'submit" class="btn btn-primary">Add new entry</button>
    {% endbuttons %}

</form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
<h2>Create new topic</h2>
{% endblock page_header %}

{% block content %}
<form method='post' action="{% url 'learning_logs:new_topic' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name="'submit" class="btn btn-primary">Add new topic</button>
    {% endbuttons %}

</form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
<h2>{{ topic }}</h2>
{% endblock page_header %}

{% block content %}
    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">Create new entry</a>
    </p>

    <ul>
    {% for entry in entries %}
        <div class="card mb-3">
            <h4 class="card-header">
                {{ entry.date_added|date:'d M Y H:i' }}
                    <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit entry</a></small>
            </h4>
            <div class="card-body">
                {{ entry.text|linebreaks }}
            </div>
        </div>
    {% empty %}
        <li>There are no entries about {{ topic }} yet.</li>
    {% endfor %}
    </ul>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
<h1>Your topics</h1>
{% endblock page_header %}


{% block content %}
<h6><a href="{% url 'learning_logs:new_topic' %}">Create new topic</a></h6>
<ul>
    {% for topic in topics %}
        <li><h3><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3></li>
    {% empty %}
        <li><h3>There are no topics yet.</h3></li>
    {% endfor %}
</ul>

{% endblock content %}